# Generated by Django 3.1.7 on 2021-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renta', '0003_auto_20210324_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='baño_privado',
            field=models.BooleanField(choices=[('Con baño privado', 'Con baño privado'), ('', '')], default=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='telefono',
            field=models.BooleanField(choices=[('Con Telefono', 'Con Telefono'), ('', '')], default=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='wifi',
            field=models.BooleanField(choices=[('Con wifi', 'Con wifi'), ('', '')], default=True),
        ),
    ]
