# Generated by Django 3.1.7 on 2021-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renta', '0004_auto_20210324_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='baño_privado',
            field=models.BooleanField(choices=[('Con baño privado', 'Con baño privado'), ('Sin baño privado', 'Sin baño privado')], default='Con baño privado'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='telefono',
            field=models.BooleanField(choices=[('Con telefono', 'Con telefono'), ('Sin telefono', 'Sin telefono')], default='Con Telefono'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='wifi',
            field=models.BooleanField(choices=[('Con wifi', 'Con wifi'), ('Sin wifi', 'Sin wifi')], default='Con wifi'),
        ),
    ]
