# Generated by Django 3.1.7 on 2021-03-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renta', '0005_auto_20210324_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='telefono',
            field=models.BooleanField(choices=[('Con telefono', 'Con telefono'), ('Sin telefono', 'Sin telefono')], default='Con telefono'),
        ),
    ]
