# Generated by Django 3.1.7 on 2021-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renta', '0006_auto_20210324_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='baño_privado',
            field=models.CharField(choices=[('Con baño privado', 'Con baño privado'), ('Sin baño privado', 'Sin baño privado')], default='Con baño privado', max_length=200),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='telefono',
            field=models.CharField(choices=[('Con telefono', 'Con telefono'), ('Sin telefono', 'Sin telefono')], default='Con telefono', max_length=200),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='wifi',
            field=models.CharField(choices=[('Con wifi', 'Con wifi'), ('Sin wifi', 'Sin wifi')], default='Con wifi', max_length=200),
        ),
    ]
